## 1. Imports

In [3]:
import pandas as pd

import os

## 2. Load Datasets into dataframe

### 2.1 Load of IR-Plag-Dataset

In [58]:
ir_plag_root = "../Dataset/IR-Plag-Dataset"

rows = []

# Reads JAVA file to save in on an attribute of the dataframe
def read_code(path):
    with open(path, "r", encoding="utf-8", errors="ignore") as file:
        return file.read()

# Walks through the dataset to read all the files and save them in a dataframe with their respective label
for current_path, dirs, files in os.walk(ir_plag_root):

    for file in files:
        full_path = os.path.join(current_path, file)

        if "non-plagiarized" in full_path:
            label = 0

        elif "plagiarized" in full_path:
            label = 1

        else:
            continue

        code = read_code(full_path)

        rows.append({
            "code": code,
            "label": label
        })

df_ir_plag = pd.DataFrame(rows)

df_ir_plag.head()

                                                code  label
0  /*\n * To change this license header, choose L...      0
1  \n/**\n *\n * @author 65FBEF05E01FAC390CB3FA07...      0
2  \n\n/**\n *\n * @author CB6AB3315634A1E4D11B09...      0
3  /*\n * To change this license header, choose L...      0
4  public class T01\n{\n   public static void mai...      0

### 2.2 Load of conplag_version_2 dataset

In [ ]:
conplag_path = "../Dataset/conplag_version_2/versions"
code_path = "../Dataset/conplag_version_2/versions/bplag_version_1"

labels = pd.read_csv(conplag_path + "/labels.csv")

train_pairs = pd.read_csv(
    conplag_path + "/train_pairs.csv",
    header=None,
    names=["pair"]
)

test_pairs = pd.read_csv(
    conplag_path + "/test_pairs.csv",
    header=None,
    names=["pair"]
)

# Separate pair into submission 1 and submission 2
train_pairs[["sub1", "sub2"]] = train_pairs["pair"].str.split("_", expand=True)
test_pairs[["sub1", "sub2"]] = test_pairs["pair"].str.split("_", expand=True)

,code1,code2,label
0,import java.util.*;\nimport java.io.*;\n\npubl...,// package com.company;\n\n\nimport com.sun.se...,0
1,import java.io.*;\nimport java.sql.SQLOutput;\...,import java.util.*;\n\npublic class D{\n pr...,0
2,// import java.io.DataInputStream; \n// import...,import java.util.*;\nimport java.io.*;\n\npubl...,0
3,import javax.swing.plaf.IconUIResource;\nimpor...,import javax.swing.plaf.IconUIResource;\nimpor...,1
4,import java.io.*;\nimport java.util.*;\n publi...,import java.io.*;\nimport java.sql.Array;\nimp...,0

## 3. Data verification

### 3.1 Verification for IR-Plag-Dataset

In [30]:
if df_ir_plag.isnull().values.any():
    print("There are null values in the dataset, data cleaning is required.")
else:
    print("There are no null values in the dataset, data is clean.")

There are no null values in the dataset, data is clean.

### 3.2 Verification for conplag_version_2 dataset

In [57]:
if df_conplag_train.isnull().values.any() or df_conplag_test.isnull().values.any():
    print("There are null values in the ConPlag dataset, data cleaning is required.")
else:
    print("There are no null values in the ConPlag dataset, data is clean.")

There are no null values in the ConPlag dataset, data is clean.